name: 'App CI Merge bot'
description: 'Automatic merges for a Gitflow workflow'
inputs:
  slack-url:  
    description: 'The slack workflow URL to notify a channel'
    required: true
  slack-channel:  
    description: 'The channel to notify'
    required: false
outputs:
  time: # id of output
    description: 'Merge complete'
runs:
  using: "composite"
  steps:
    - run: git config user.email "app-release-ci@noreply.com" && git config user.name "App Release CI"
      shell: bash
    - run: perl ${{ github.action_path }}/merge_report.pl ${{ inputs.slack-url }} ${{ inputs.slack-channel }} mergeOnly
      shell: bash